// <auto-generated />
using GestionResidenciaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionResidenciaApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260409163257_PrimeraMigracion")]
    partial class PrimeraMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionResidenciaApi.Models.Apartamentos", b =>
                {
                    b.Property<int>("UnidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnidadId"));

                    b.HasKey("UnidadId");

                    b.ToTable("Apartamentos");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.AuditoriaLogin", b =>
                {
                    b.Property<int>("AuditoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditoriaId"));

                    b.HasKey("AuditoriaId");

                    b.ToTable("AuditoriaLogin");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.BitacoraVigilancia", b =>
                {
                    b.Property<int>("BitacoraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BitacoraId"));

                    b.HasKey("BitacoraId");

                    b.ToTable("BitacoraVigilancia");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Conjunto", b =>
                {
                    b.Property<int>("ConjuntoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConjuntoId"));

                    b.HasKey("ConjuntoId");

                    b.ToTable("Conjunto");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.CuotaAdministracion", b =>
                {
                    b.Property<int>("CuotaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CuotaId"));

                    b.HasKey("CuotaId");

                    b.ToTable("CuotaAdministracion");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.EstadoCuota", b =>
                {
                    b.Property<int>("EstadoCuotaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoCuotaId"));

                    b.HasKey("EstadoCuotaId");

                    b.ToTable("EmpleEstadoCuotaado");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.EstadoParqueadero", b =>
                {
                    b.Property<int>("EstadoParqueaderoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoParqueaderoId"));

                    b.HasKey("EstadoParqueaderoId");

                    b.ToTable("EstadoParqueadero");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Ingreso", b =>
                {
                    b.Property<int>("IngresoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngresoId"));

                    b.HasKey("IngresoId");

                    b.ToTable("Ingreso");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Mantenimiento", b =>
                {
                    b.Property<int>("MantenimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MantenimientoId"));

                    b.HasKey("MantenimientoId");

                    b.ToTable("Mantenimiento");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Mensajeria", b =>
                {
                    b.Property<int>("MensajeriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MensajeriaId"));

                    b.HasKey("MensajeriaId");

                    b.ToTable("Mensajeria");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.MetodoPago", b =>
                {
                    b.Property<int>("MetodoPagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetodoPagoId"));

                    b.HasKey("MetodoPagoId");

                    b.ToTable("MetodoPago");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoId"));

                    b.HasKey("PagoId");

                    b.ToTable("Pago");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.PagoDetalle", b =>
                {
                    b.Property<int>("PagoDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoDetalleId"));

                    b.HasKey("PagoDetalleId");

                    b.ToTable("PagoDetalle");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Parqueadero", b =>
                {
                    b.Property<int>("ParqueaderoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParqueaderoId"));

                    b.HasKey("ParqueaderoId");

                    b.ToTable("Parqueadero");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.ParqueaderoVisitante", b =>
                {
                    b.Property<int>("ParqueaderoVisitanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParqueaderoVisitanteId"));

                    b.HasKey("ParqueaderoVisitanteId");

                    b.ToTable("ParqueaderoVisitante");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Permiso", b =>
                {
                    b.Property<int>("PermisoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermisoId"));

                    b.HasKey("PermisoId");

                    b.ToTable("Permiso");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Persona", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonaId"));

                    b.HasKey("PersonaId");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservaId"));

                    b.HasKey("ReservaId");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.ResidenteUnidad", b =>
                {
                    b.Property<int>("ResidenteUnidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResidenteUnidadId"));

                    b.HasKey("ResidenteUnidadId");

                    b.ToTable("ResidenteUnidad");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.HasKey("RolId");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.RolPermiso", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.HasKey("RolId");

                    b.ToTable("RolPermiso");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.TipoEvento", b =>
                {
                    b.Property<int>("TipoEventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoEventoId"));

                    b.HasKey("TipoEventoId");

                    b.ToTable("TipoEvento");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.TipoIngreso", b =>
                {
                    b.Property<int>("TipoIngresoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoIngresoId"));

                    b.HasKey("TipoIngresoId");

                    b.ToTable("TipoIngreso");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.TipoMantenimiento", b =>
                {
                    b.Property<int>("TipoMantenimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoMantenimientoId"));

                    b.HasKey("TipoMantenimientoId");

                    b.ToTable("TipoMantenimiento");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.TipoParqueadero", b =>
                {
                    b.Property<int>("TipoParqueaderoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoParqueaderoId"));

                    b.HasKey("TipoParqueaderoId");

                    b.ToTable("TipoParqueadero");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Torre", b =>
                {
                    b.Property<int>("TorreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TorreId"));

                    b.HasKey("TorreId");

                    b.ToTable("Torre");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Visitante", b =>
                {
                    b.Property<int>("VisitanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitanteId"));

                    b.HasKey("VisitanteId");

                    b.ToTable("Visitante");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.ZonaComun", b =>
                {
                    b.Property<int>("ZonaComunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZonaComunId"));

                    b.HasKey("ZonaComunId");

                    b.ToTable("ZonaComun");
                });
#pragma warning restore 612, 618
        }
    }
}
