// <auto-generated />
using System;
using GestionResidenciaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionResidenciaApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260421212713_FixCascadePaths")]
    partial class FixCascadePaths
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionResidenciaApi.Models.Apartamentos", b =>
                {
                    b.Property<int>("UnidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnidadId"));

                    b.Property<int>("Area")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TorreId")
                        .HasColumnType("int");

                    b.HasKey("UnidadId");

                    b.HasIndex("TorreId");

                    b.ToTable("Apartamentos");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.AuditoriaLogin", b =>
                {
                    b.Property<int>("AuditoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditoriaId"));

                    b.Property<bool>("Exitoso")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaIntento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("AuditoriaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AuditoriaLogin");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.BitacoraVigilancia", b =>
                {
                    b.Property<int>("BitacoraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BitacoraId"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("IngresoId")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoEventoId")
                        .HasColumnType("int");

                    b.Property<int>("UnidadId")
                        .HasColumnType("int");

                    b.Property<int>("VigilanteId")
                        .HasColumnType("int");

                    b.HasKey("BitacoraId");

                    b.HasIndex("IngresoId");

                    b.HasIndex("TipoEventoId");

                    b.HasIndex("UnidadId");

                    b.HasIndex("VigilanteId");

                    b.ToTable("BitacoraVigilancia");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Conjunto", b =>
                {
                    b.Property<int>("ConjuntoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConjuntoId"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConjuntoId");

                    b.ToTable("Conjunto");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.CuotaAdministracion", b =>
                {
                    b.Property<int>("CuotaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CuotaId"));

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaLimite")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Periodo")
                        .HasColumnType("date");

                    b.Property<decimal>("SaldoPendiente")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnidadId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CuotaId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("UnidadId");

                    b.ToTable("CuotaAdministracion");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Estado", b =>
                {
                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstadoId");

                    b.ToTable("Estado");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Ingreso", b =>
                {
                    b.Property<int>("IngresoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngresoId"));

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHoraIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraSalida")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombrePersona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoIngresoId")
                        .HasColumnType("int");

                    b.Property<int>("UnidadId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("Vehiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitanteId")
                        .HasColumnType("int");

                    b.HasKey("IngresoId");

                    b.HasIndex("TipoIngresoId");

                    b.HasIndex("UnidadId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VisitanteId");

                    b.ToTable("Ingreso");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Mantenimiento", b =>
                {
                    b.Property<int>("MantenimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MantenimientoId"));

                    b.Property<decimal>("Costo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoMantenimientoId")
                        .HasColumnType("int");

                    b.Property<int>("UnidadId")
                        .HasColumnType("int");

                    b.Property<int>("ZonaComunId")
                        .HasColumnType("int");

                    b.HasKey("MantenimientoId");

                    b.HasIndex("TipoMantenimientoId");

                    b.HasIndex("UnidadId");

                    b.HasIndex("ZonaComunId");

                    b.ToTable("Mantenimiento");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Mensajeria", b =>
                {
                    b.Property<int>("MensajeriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MensajeriaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Guia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("MensajeriaId");

                    b.HasIndex("UnidadId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Mensajeria");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.MetodoPago", b =>
                {
                    b.Property<int>("MetodoPagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetodoPagoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MetodoPagoId");

                    b.ToTable("MetodoPago");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoId"));

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetodoPagoId")
                        .HasColumnType("int");

                    b.Property<string>("PagoObservacionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PagoId");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pago");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.PagoDetalle", b =>
                {
                    b.Property<int>("PagoDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoDetalleId"));

                    b.Property<int>("CuotaId")
                        .HasColumnType("int");

                    b.Property<int>("PagoId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorAbonado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PagoDetalleId");

                    b.HasIndex("CuotaId");

                    b.HasIndex("PagoId");

                    b.ToTable("PagoDetalle");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Parqueadero", b =>
                {
                    b.Property<int>("ParqueaderoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParqueaderoId"));

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoParqueaderoId")
                        .HasColumnType("int");

                    b.Property<int>("UnidadId")
                        .HasColumnType("int");

                    b.HasKey("ParqueaderoId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("TipoParqueaderoId");

                    b.HasIndex("UnidadId");

                    b.ToTable("Parqueadero");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.ParqueaderoVisitante", b =>
                {
                    b.Property<int>("ParqueaderoVisitanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParqueaderoVisitanteId"));

                    b.Property<DateTime>("FechaHoraIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraSalida")
                        .HasColumnType("datetime2");

                    b.Property<int>("IngresoId")
                        .HasColumnType("int");

                    b.Property<int>("ParqueaderoId")
                        .HasColumnType("int");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VisitanteId")
                        .HasColumnType("int");

                    b.HasKey("ParqueaderoVisitanteId");

                    b.HasIndex("IngresoId");

                    b.HasIndex("ParqueaderoId");

                    b.HasIndex("VisitanteId");

                    b.ToTable("ParqueaderoVisitante");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Permiso", b =>
                {
                    b.Property<int>("PermisoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermisoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PermisoId");

                    b.ToTable("Permiso");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Persona", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonaId"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonaId");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservaId"));

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("ZonaComunId")
                        .HasColumnType("int");

                    b.HasKey("ReservaId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ZonaComunId");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.ResidenteUnidad", b =>
                {
                    b.Property<int>("ResidenteUnidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResidenteUnidadId"));

                    b.Property<int>("EsPropietario")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ResidenteUnidadId");

                    b.HasIndex("UnidadId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ResidenteUnidad");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolId");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.RolPermiso", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("PermisoId")
                        .HasColumnType("int");

                    b.HasKey("RolId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("RolPermiso");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.TipoEvento", b =>
                {
                    b.Property<int>("TipoEventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoEventoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoEventoId");

                    b.ToTable("TipoEvento");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.TipoIngreso", b =>
                {
                    b.Property<int>("TipoIngresoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoIngresoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoIngresoId");

                    b.ToTable("TipoIngreso");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.TipoMantenimiento", b =>
                {
                    b.Property<int>("TipoMantenimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoMantenimientoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoMantenimientoId");

                    b.ToTable("TipoMantenimiento");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.TipoParqueadero", b =>
                {
                    b.Property<int>("TipoParqueaderoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoParqueaderoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoParqueaderoId");

                    b.ToTable("TipoParqueadero");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Torre", b =>
                {
                    b.Property<int>("TorreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TorreId"));

                    b.Property<int>("ConjuntoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TorreId");

                    b.HasIndex("ConjuntoId");

                    b.ToTable("Torre");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("RolId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Visitante", b =>
                {
                    b.Property<int>("VisitanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitanteId"));

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VisitanteId");

                    b.ToTable("Visitante");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.ZonaComun", b =>
                {
                    b.Property<int>("ZonaComunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZonaComunId"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<int>("ConjuntoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequierePago")
                        .HasColumnType("bit");

                    b.Property<decimal>("ValorHora")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ZonaComunId");

                    b.HasIndex("ConjuntoId");

                    b.ToTable("ZonaComun");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Apartamentos", b =>
                {
                    b.HasOne("GestionResidenciaApi.Models.Torre", "Torre")
                        .WithMany("Apartamentos")
                        .HasForeignKey("TorreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Torre");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.AuditoriaLogin", b =>
                {
                    b.HasOne("GestionResidenciaApi.Models.Usuario", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.BitacoraVigilancia", b =>
                {
                    b.HasOne("GestionResidenciaApi.Models.Ingreso", "Ingreso")
                        .WithMany("Bitacoras")
                        .HasForeignKey("IngresoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionResidenciaApi.Models.TipoEvento", "TipoEvento")
                        .WithMany("Bitacoras")
                        .HasForeignKey("TipoEventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionResidenciaApi.Models.Apartamentos", "Unidad")
                        .WithMany()
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionResidenciaApi.Models.Usuario", "Vigilante")
                        .WithMany("Vigilancias")
                        .HasForeignKey("VigilanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingreso");

                    b.Navigation("TipoEvento");

                    b.Navigation("Unidad");

                    b.Navigation("Vigilante");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.CuotaAdministracion", b =>
                {
                    b.HasOne("GestionResidenciaApi.Models.Estado", "Estado")
                        .WithMany("Cuotas")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionResidenciaApi.Models.Apartamentos", "Unidad")
                        .WithMany("Cuotas")
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Ingreso", b =>
                {
                    b.HasOne("GestionResidenciaApi.Models.TipoIngreso", "TipoIngreso")
                        .WithMany("Ingresos")
                        .HasForeignKey("TipoIngresoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionResidenciaApi.Models.Apartamentos", "Unidad")
                        .WithMany("Ingresos")
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionResidenciaApi.Models.Usuario", "Usuario")
                        .WithMany("Ingresos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionResidenciaApi.Models.Visitante", "Visitante")
                        .WithMany("Ingresos")
                        .HasForeignKey("VisitanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoIngreso");

                    b.Navigation("Unidad");

                    b.Navigation("Usuario");

                    b.Navigation("Visitante");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Mantenimiento", b =>
                {
                    b.HasOne("GestionResidenciaApi.Models.TipoMantenimiento", "TipoMantenimiento")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("TipoMantenimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionResidenciaApi.Models.Apartamentos", "Unidad")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionResidenciaApi.Models.ZonaComun", "ZonaComun")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("ZonaComunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoMantenimiento");

                    b.Navigation("Unidad");

                    b.Navigation("ZonaComun");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Mensajeria", b =>
                {
                    b.HasOne("GestionResidenciaApi.Models.Apartamentos", "Unidad")
                        .WithMany("Mensajerias")
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionResidenciaApi.Models.Usuario", "Usuario")
                        .WithMany("Mensajerias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unidad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Pago", b =>
                {
                    b.HasOne("GestionResidenciaApi.Models.MetodoPago", "MetodoPago")
                        .WithMany("Pagos")
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionResidenciaApi.Models.Usuario", "Usuario")
                        .WithMany("Pagos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetodoPago");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.PagoDetalle", b =>
                {
                    b.HasOne("GestionResidenciaApi.Models.CuotaAdministracion", "Cuota")
                        .WithMany("PagoDetalles")
                        .HasForeignKey("CuotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionResidenciaApi.Models.Pago", "Pago")
                        .WithMany("PagoDetalles")
                        .HasForeignKey("PagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuota");

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Parqueadero", b =>
                {
                    b.HasOne("GestionResidenciaApi.Models.Estado", "Estado")
                        .WithMany("Parqueaderos")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionResidenciaApi.Models.TipoParqueadero", "TipoParqueadero")
                        .WithMany("Parqueaderos")
                        .HasForeignKey("TipoParqueaderoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionResidenciaApi.Models.Apartamentos", "Unidad")
                        .WithMany("Parqueaderos")
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("TipoParqueadero");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.ParqueaderoVisitante", b =>
                {
                    b.HasOne("GestionResidenciaApi.Models.Ingreso", "Ingreso")
                        .WithMany("ParqueaderoVisitantes")
                        .HasForeignKey("IngresoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionResidenciaApi.Models.Parqueadero", "Parqueadero")
                        .WithMany("ParqueaderoVisitantes")
                        .HasForeignKey("ParqueaderoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionResidenciaApi.Models.Visitante", null)
                        .WithMany("ParqueaderoVisitantes")
                        .HasForeignKey("VisitanteId");

                    b.Navigation("Ingreso");

                    b.Navigation("Parqueadero");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Reserva", b =>
                {
                    b.HasOne("GestionResidenciaApi.Models.Estado", "Estado")
                        .WithMany("Reservas")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionResidenciaApi.Models.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionResidenciaApi.Models.ZonaComun", "ZonaComun")
                        .WithMany("Reservas")
                        .HasForeignKey("ZonaComunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Usuario");

                    b.Navigation("ZonaComun");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.ResidenteUnidad", b =>
                {
                    b.HasOne("GestionResidenciaApi.Models.Apartamentos", "Unidad")
                        .WithMany("Residentes")
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionResidenciaApi.Models.Usuario", "Usuario")
                        .WithMany("ResidenteUnidades")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unidad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.RolPermiso", b =>
                {
                    b.HasOne("GestionResidenciaApi.Models.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionResidenciaApi.Models.Rol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Torre", b =>
                {
                    b.HasOne("GestionResidenciaApi.Models.Conjunto", "Conjunto")
                        .WithMany("Torres")
                        .HasForeignKey("ConjuntoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conjunto");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Usuario", b =>
                {
                    b.HasOne("GestionResidenciaApi.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionResidenciaApi.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.ZonaComun", b =>
                {
                    b.HasOne("GestionResidenciaApi.Models.Conjunto", "Conjunto")
                        .WithMany("ZonasComunes")
                        .HasForeignKey("ConjuntoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conjunto");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Apartamentos", b =>
                {
                    b.Navigation("Cuotas");

                    b.Navigation("Ingresos");

                    b.Navigation("Mantenimientos");

                    b.Navigation("Mensajerias");

                    b.Navigation("Parqueaderos");

                    b.Navigation("Residentes");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Conjunto", b =>
                {
                    b.Navigation("Torres");

                    b.Navigation("ZonasComunes");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.CuotaAdministracion", b =>
                {
                    b.Navigation("PagoDetalles");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Estado", b =>
                {
                    b.Navigation("Cuotas");

                    b.Navigation("Parqueaderos");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Ingreso", b =>
                {
                    b.Navigation("Bitacoras");

                    b.Navigation("ParqueaderoVisitantes");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.MetodoPago", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Pago", b =>
                {
                    b.Navigation("PagoDetalles");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Parqueadero", b =>
                {
                    b.Navigation("ParqueaderoVisitantes");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Permiso", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Rol", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.TipoEvento", b =>
                {
                    b.Navigation("Bitacoras");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.TipoIngreso", b =>
                {
                    b.Navigation("Ingresos");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.TipoMantenimiento", b =>
                {
                    b.Navigation("Mantenimientos");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.TipoParqueadero", b =>
                {
                    b.Navigation("Parqueaderos");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Torre", b =>
                {
                    b.Navigation("Apartamentos");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Usuario", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Ingresos");

                    b.Navigation("Mensajerias");

                    b.Navigation("Pagos");

                    b.Navigation("Reservas");

                    b.Navigation("ResidenteUnidades");

                    b.Navigation("Vigilancias");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.Visitante", b =>
                {
                    b.Navigation("Ingresos");

                    b.Navigation("ParqueaderoVisitantes");
                });

            modelBuilder.Entity("GestionResidenciaApi.Models.ZonaComun", b =>
                {
                    b.Navigation("Mantenimientos");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
